version: '3.8'

services:
  api-gateway:
    build:
      context: ./autoprogrammer-api
      dockerfile: Dockerfile
    container_name: autoprogrammer-api-gateway
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - AI_SERVICE_URL=http://ai-service:5000
      - FRONTEND_URLS=http://localhost:5173,http://localhost:5174
      - RATE_LIMIT_MAX_REQUESTS=60
      - RATE_LIMIT_WINDOW_MS=60000
    volumes:
      - ./logs/api-gateway:/app/logs
    depends_on:
      - ai-service
    networks:
      - autoprogrammer-network

  ai-service:
    build:
      context: ./autoprogrammer-ai-service
      dockerfile: Dockerfile
    container_name: autoprogrammer-ai-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - DEEPSEEK_API_URL=https://api.deepseek.com/v1/chat/completions
      - DEEPSEEK_MODEL=deepseek-coder-plus
      - DEEPSEEK_MAX_TOKENS=4096
      - DEEPSEEK_TEMPERATURE=0.2
      - GATEWAY_URL=http://api-gateway:4000
      - RATE_LIMIT_MAX_REQUESTS=30
      - RATE_LIMIT_WINDOW_MS=60000
    volumes:
      - ./logs/ai-service:/app/logs
    networks:
      - autoprogrammer-network

  ui:
    build:
      context: ./autoprogrammer-ui
      dockerfile: Dockerfile
    container_name: autoprogrammer-ui
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - api-gateway
    networks:
      - autoprogrammer-network

networks:
  autoprogrammer-network:
    driver: bridge 