version: '3.8'

services:
  # Main AutoProgrammer application
  app:
    build: .
    container_name: autoprogrammer-app
    ports:
      - "3000:3000"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - NODE_ENV=production
      - ENABLE_CURSOR_INTEGRATION=true
    depends_on:
      - output-service
    networks:
      - autoprogrammer-network

  # Output processing microservice
  output-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoprogrammer-output-service
    command: node ./services/output-service.js
    volumes:
      - ./outputs:/app/outputs
    environment:
      - NODE_ENV=production
      - OUTPUT_DIR=/app/outputs
    networks:
      - autoprogrammer-network

  # Cursor integration microservice
  cursor-integration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoprogrammer-cursor-integration
    command: ./last-resort.command
    volumes:
      - ./outputs:/app/outputs
      - ${HOME}/Desktop:/Desktop
    environment:
      - NODE_ENV=production
      - DESKTOP_PATH=/Desktop
    networks:
      - autoprogrammer-network

networks:
  autoprogrammer-network:
    driver: bridge 