[build]
  command = "cd autoprogrammer-ui && npm install && npm run build"
  publish = "autoprogrammer-ui/dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/ai/*"
  to = "/.netlify/functions/ai/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 